name: "auto deploy to heruko"

on:
  push:
    branches:
      - master

env:
  HEROKU_API_KEY: ${{ secrets.DOCKER_PASS }}
  APP_NAME: ${{ 'ali-todos-app' }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: registry login
        run: docker login --username=_ --password=$HEROKU_API_KEY  registry.heroku.com

      - name: docker build
        run: docker build --target=production -t registry.heroku.com/$APP_NAME/web .

      - name: docker push
        run: docker push registry.heroku.com/ali-todos-app/web

      - name: release
        run: heroku container:release web -a $APP_NAME
        # release registry.heroku.com/ali-todos-app/web
