name: "auto deploy to heruko"

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: registry login
        run: docker login --username=_ --password=${{secrets.DOCKER_PASS}}  registry.heroku.com

      - name: docker build
        run: docker build --target=production -t registry.heroku.com/ali-todos-app/web .

      - name: docker push
        run: docker push registry.heroku.com/ali-todos-app/web

      - name: release
        run: heroku container:release web -a ali-todos-app
        # release registry.heroku.com/ali-todos-app/web
